// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoY0S7LaEUs0dWAo1192aeVqvdmUsI8Qs',
    appId: '1:409393105099:web:6e7b2eb2ad91827c8db34e',
    messagingSenderId: '409393105099',
    projectId: 'item-minder',
    authDomain: 'item-minder.firebaseapp.com',
    databaseURL: 'https://item-minder-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'item-minder.firebasestorage.app',
    measurementId: 'G-ZFWC3L8E88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGWPCMpP1tW7qsn4_TU7k4w_-UEGRrP_E',
    appId: '1:409393105099:android:97f8819c082cbfb98db34e',
    messagingSenderId: '409393105099',
    projectId: 'item-minder',
    databaseURL: 'https://item-minder-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'item-minder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtsT8cMqagk1UKYZMlf6tKl75qBnzwRa8',
    appId: '1:409393105099:ios:b15c7a92ae3065ee8db34e',
    messagingSenderId: '409393105099',
    projectId: 'item-minder',
    databaseURL: 'https://item-minder-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'item-minder.firebasestorage.app',
    iosBundleId: 'com.example.itemMinderFlutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtsT8cMqagk1UKYZMlf6tKl75qBnzwRa8',
    appId: '1:409393105099:ios:b15c7a92ae3065ee8db34e',
    messagingSenderId: '409393105099',
    projectId: 'item-minder',
    databaseURL: 'https://item-minder-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'item-minder.firebasestorage.app',
    iosBundleId: 'com.example.itemMinderFlutterapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoY0S7LaEUs0dWAo1192aeVqvdmUsI8Qs',
    appId: '1:409393105099:web:03af04ebaa20acc88db34e',
    messagingSenderId: '409393105099',
    projectId: 'item-minder',
    authDomain: 'item-minder.firebaseapp.com',
    databaseURL: 'https://item-minder-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'item-minder.firebasestorage.app',
    measurementId: 'G-R1WSC4LP0T',
  );
}
